### ISSUE TITLE
Weblogic Deploy error 

### ISSUE THREAD

**Issue by polaskj** [joergrech/KickstartWithBootstrap#26]
Fresh projects fail to deploy on Weblogic container. 

java.io.FileNotFoundException: C:\bwl\user_projects\domains\WLSDomain.\grails-a
pp\i18n

**Comment by joergrech** [comment]
Hi, have you made an error that you solved by yourself (e.g, no I18N files or old Kickstart plugin) or did you "repair" the plugin? The error is typical for a wrong path to the I18N files and is caused by the container. It should work with Tomcat but I did not test ist with Weblogic.

**Comment by polaskj** [comment]
After I posted the issue I noticed the patch for 0.8.8 and closed the issue
temporarily. After testing and applying the patch, I am still getting the
error.The full stack trace is below. The project is a new 2.1.2 project and
has all default settings with a basic domain where the controllers and
views are generated. This was done after running the kickstart command. I
am running on Weblogic 9.2.
Thanks for the quick response

> 2012-12-29 09:25:32,148 [[ACTIVE] ExecuteThread: '0' for queue:
> 'weblogic.kernel
> .Default (self-tuning)'] ERROR plugins.DefaultGrailsPluginManager  - Error
> confi
> guring dynamic methods for plugin [resources:1.1.6]:
> java.lang.NoSuchMethodError
> : org.mozilla.javascript.tools.shell.Global: method <init>()V not found
> org.codehaus.groovy.runtime.InvokerInvocationException:
> java.lang.NoSuchMethodEr
> ror: org.mozilla.javascript.tools.shell.Global: method <init>()V not found
>         at
> weblogic.servlet.internal.EventsManager$FireContextListenerAction.run
> (EventsManager.java:458)
>         at
> weblogic.security.acl.internal.AuthenticatedSubject.doAs(Authenticate
> dSubject.java:321)
>         at
> weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(Eve
> ntsManager.java:168)
>         at
> weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAp
> pServletContext.java:1744)
>         at
> weblogic.servlet.internal.WebAppServletContext.start(WebAppServletCon
> text.java:2918)
>         at
> weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.jav
> a:973)
>         at
> weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:361)
>         at
> weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleSta
> teDriver.java:204)
>         at
> weblogic.application.utils.StateMachineDriver.nextState(StateMachineD
> river.java:26)
>         at
> weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStat
> eDriver.java:60)
>         at
> weblogic.application.internal.flow.ScopedModuleDriver.start(ScopedMod
> uleDriver.java:200)
>         at
> weblogic.application.internal.flow.ModuleListenerInvoker.start(Module
> ListenerInvoker.java:117)
>         at
> weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleSta
> teDriver.java:204)
>         at
> weblogic.application.utils.StateMachineDriver.nextState(StateMachineD
> river.java:26)
>         at
> weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStat
> eDriver.java:60)
>         at
> weblogic.application.internal.flow.StartModulesFlow.activate(StartMod
> ulesFlow.java:27)
>         at
> weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.ja
> va:635)
>         at
> weblogic.application.utils.StateMachineDriver.nextState(StateMachineD
> river.java:26)
>         at
> weblogic.application.internal.BaseDeployment.activate(BaseDeployment.
> java:212)
>         at
> weblogic.application.internal.DeploymentStateChecker.activate(Deploym
> entStateChecker.java:154)
>         at
> weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(Ap
> pContainerInvoker.java:80)
>         at
> weblogic.deploy.internal.targetserver.operations.AbstractOperation.ac
> tivate(AbstractOperation.java:566)
>         at
> weblogic.deploy.internal.targetserver.operations.ActivateOperation.ac
> tivateDeployment(ActivateOperation.java:136)
>         at
> weblogic.deploy.internal.targetserver.operations.ActivateOperation.do
> Commit(ActivateOperation.java:104)
>         at
> weblogic.deploy.internal.targetserver.operations.StartOperation.doCom
> mit(StartOperation.java:139)
>         at
> weblogic.deploy.internal.targetserver.operations.AbstractOperation.co
> mmit(AbstractOperation.java:320)
>         at
> weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploym
> entCommit(DeploymentManager.java:816)
>         at
> weblogic.deploy.internal.targetserver.DeploymentManager.activateDeplo
> ymentList(DeploymentManager.java:1223)
>         at
> weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(
> DeploymentManager.java:434)
>         at
> weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.com
> mit(DeploymentServiceDispatcher.java:161)
>         at
> weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallb
> ackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:181)
>         at
> weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallb
> ackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:12)
>         at
> weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallb
> ackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:67)
>         at
> weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTunin
> gWorkManagerImpl.java:464)
>         at weblogic.work.ExecuteThread.execute(ExecuteThread.java:200)
>         at weblogic.work.ExecuteThread.run(ExecuteThread.java:172)
> Caused by: java.lang.NoSuchMethodError:
> org.mozilla.javascript.tools.shell.Globa
> l: method <init>()V not found
>         at org.lesscss.LessCompiler.init(LessCompiler.java:197)
>         at org.lesscss.LessCompiler.compile(LessCompiler.java:229)
>         at org.lesscss.LessCompiler.compile(LessCompiler.java:302)
>         at org.lesscss.LessCompiler.compile(LessCompiler.java:326)
>         at org.lesscss.LessCompiler.compile(LessCompiler.java:292)
>         at org.lesscss.LessCompiler.compile(LessCompiler.java:279)
>         at LesscssResourceMapper.map(LesscssResourceMapper.groovy:31)
>         at
> org.grails.plugin.resource.mapper.ResourceMapper.invoke(ResourceMappe
> r.groovy:139)
>         at
> org.grails.plugin.resource.mapper.ResourceMapper.invokeIfNotExcluded(
> ResourceMapper.groovy:128)
>         at
> org.grails.plugin.resource.ResourceProcessor.applyMappers(ResourcePro
> cessor.groovy:587)
>         at
> org.grails.plugin.resource.ResourceProcessor.prepareResource(Resource
> Processor.groovy:533)
>         at
> org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredRe
> source_closure12.doCall(ResourceProcessor.groovy:602)
>         at
> org.grails.plugin.resource.util.ResourceMetaStore.addDeclaredResource
> (ResourceMetaStore.groovy:29)
>         at
> org.grails.plugin.resource.ResourceProcessor.prepareSingleDeclaredRes
> ource(ResourceProcessor.groovy:600)
>         at
> org.grails.plugin.resource.ResourceProcessor$_prepareResourceBatch_cl
> osure14.doCall(ResourceProcessor.groovy:625)
>         at
> org.grails.plugin.resource.ResourceProcessorBatch.each(ResourceProces
> sorBatch.groovy:8)
>         at
> org.grails.plugin.resource.ResourceProcessor.prepareResourceBatch(Res
> ourceProcessor.groovy:621)
>         at
> org.grails.plugin.resource.ResourceProcessor.resourcesChanged(Resourc
> eProcessor.groovy:804)
>         at
> org.grails.plugin.resource.ResourceProcessor.loadModules(ResourceProc
> essor.groovy:800)
>         at
> org.grails.plugin.resource.ResourceProcessor.reloadAll(ResourceProces
> sor.groovy:1056)
>         at
> ResourcesGrailsPlugin$_closure3.doCall(ResourcesGrailsPlugin.groovy:1
> 72)
>         ... 36 more
> <Dec 29, 2012 9:25:33 AM EST> <Error> <Deployer> <BEA-149265> <Failure
> occurred
> in the execution of deployment request with ID '1356791119511' for task
> '0'. Err
> or is: 'weblogic.application.ModuleException: '
> weblogic.application.ModuleException:
>         at
> weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.jav
> a:975)
>         at
> weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:361)
>         at
> weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleSta
> teDriver.java:204)
>         at
> weblogic.application.utils.StateMachineDriver.nextState(StateMachineD
> river.java:26)
>         at
> weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStat
> eDriver.java:60)
>         Truncated. see log file for complete stacktrace
> java.io.FileNotFoundException:
> C:\bwl\user_projects\domains\WLSDomain.\grails-a
> pp\i18n
>         at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.checkDir(DefaultGroo
> vyMethods.java:16448)
>         at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(Defa
> ultGroovyMethods.java:16527)
>         at
> org.codehaus.groovy.runtime.DefaultGroovyMethods.eachFileRecurse(Defa
> ultGroovyMethods.java:16766)
>         at org.codehaus.groovy.runtime.dgm$187.invoke(Unknown Source)
>         at
> org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMetho
> dSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
>         Truncated. see log file for complete stacktrace
> 
> <Dec 29, 2012 9:25:33 AM EST> <Error> <Deployer> <BEA-149202> <Encountered
> an ex
> ception while attempting to commit the 7 task for the application
> 'kickstart-tes
> t'.>

**Comment by joergrech** [comment]
I assume that "C:\bwl\user_projects\domains\WLSDomain" is the root of your project and not the root of your Weblogic system - correct? 

If so the path to your I18N files is incorrect. I'll look into it - a quick fix would be to comment the method/closure "doWithApplicationContext" within the file KickstartWithBootstrapGrailsPlugin.groovy within the Kickstart plugin (you should be able to get there via your editor or look into the directory ".grails/2.1.2/projects/WLSDomain/plugins/Kickstart..." in your home directory). The only downside should be that the language switcher should not work anymore (but you could fix this manually)

**Comment by polaskj** [comment]
Correct. Hard coding the path works fine. As it turns out this is a shortcoming in Weblogic 9.2 when retrieving ServletContext.getRealPath as explained with workaround here: http://ananthkannan.blogspot.com/2009/12/servletcontextgetrealpath-returns-null.html?m=1 .

Closing issue
